#ifndef HELPER_H
#define HELPER_H
#include <QTcpServer>
#include <QDebug>
#include <QTcpSocket>
#include <QThread>
#include <QAbstractSocket>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonValue>
#include <QDateTime>
#include <QVariantList>
#include <QSqlDatabase>
#include <QMessageBox>
#include <QDebug>
#include <QSqlError>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlQueryModel>
#endif // HELPER_H
